version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: guess_game_postgres_dev
    environment:
      POSTGRES_DB: guess_game
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - guess_game_network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: guess_game_backend_dev
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      FLASK_DEBUG: 1
      FLASK_DB_TYPE: postgres
      FLASK_DB_USER: postgres
      FLASK_DB_NAME: guess_game
      FLASK_DB_PASSWORD: secretpass
      FLASK_DB_HOST: postgres
      FLASK_DB_PORT: 5432
      JWT_SECRET_KEY: dev-secret-key
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - guess_game_network
    restart: unless-stopped

volumes:
  postgres_dev_data:
    driver: local

networks:
  guess_game_network:
    driver: bridge
